name = "copy-sync"
main = "src/index.ts"
compatibility_date = "2024-03-09"

[[kv_namespaces]]
binding = "COPY_KV"
id = "62639355977e42e9871adae5c553749d"

[route]
pattern = "copy.io99.xyz/*"
custom_domain = true
